/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CompleteProject;

import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.SwingUtilities;
import java.util.regex.*;

/**
 *
 * @author 18JBond
 */
public class TabbedProject extends javax.swing.JFrame {

    int columns;
    int rows;

    int totalMineCount = -1;//to be determined by which difficulty selector is chosen default -1?
    int[][] buttons_As_Mines;
    boolean[][] buttons_cleared;
    boolean game_in_progress = false;
    JButton[][] buttons;
    int flagged = 0;
    Color background = new Color(243, 215, 175);
    String accountName;
    int elapsedTime = 0;

    public TabbedProject() {
        initComponents();
        this.getContentPane().setBackground(background);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BaseTabbedPnl = new javax.swing.JTabbedPane();
        LoginPnl = new javax.swing.JPanel();
        Title1lbl = new javax.swing.JLabel();
        LoginPasswordFld = new javax.swing.JPasswordField();
        LoginUsernameFld = new javax.swing.JTextField();
        loginSubmitBtn = new javax.swing.JToggleButton();
        loginSubmitBtn1 = new javax.swing.JToggleButton();
        CreateNewPnl = new javax.swing.JPanel();
        CreateNewusernameFld = new javax.swing.JTextField();
        CreateNewPswrdFld2 = new javax.swing.JPasswordField();
        CreateNewPswrdFld1 = new javax.swing.JPasswordField();
        CreateNewSubmitBtn = new javax.swing.JToggleButton();
        CreateNewSubmitBtn1 = new javax.swing.JToggleButton();
        Title1lbl1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        HomePnl = new javax.swing.JPanel();
        EasySelectBtn = new javax.swing.JButton();
        MediumSelectBtn = new javax.swing.JButton();
        HardSelectBtn = new javax.swing.JButton();
        homeHelpbtn = new javax.swing.JButton();
        statisticsBtn = new javax.swing.JButton();
        homeUsernamefld = new javax.swing.JTextField();
        Title1lbl2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        GameBasePnl = new javax.swing.JPanel();
        GameInfoPnl = new javax.swing.JPanel();
        helpGameBtn = new javax.swing.JButton();
        quitBtn1 = new javax.swing.JButton();
        flagNumberfld = new javax.swing.JTextField();
        timerLbl = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        GameGridPnl = new javax.swing.JPanel();
        HelpPnl = new javax.swing.JPanel();
        Title1lbl3 = new javax.swing.JLabel();
        helpHomebtn = new javax.swing.JButton();
        backToGamebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        UserStatsPnl = new javax.swing.JPanel();
        statisticsUsernamefld = new javax.swing.JTextField();
        winLossfld = new javax.swing.JTextField();
        Title1lbl4 = new javax.swing.JLabel();
        statisticsHomebtn = new javax.swing.JButton();
        tilesClearedfld = new javax.swing.JTextField();
        gamesWonfld = new javax.swing.JTextField();
        gamesPlayedfdl = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        WinPnl = new javax.swing.JPanel();
        Title2Lbl2 = new javax.swing.JLabel();
        playAgainWinbtn = new javax.swing.JButton();
        LossPnl = new javax.swing.JPanel();
        Title2Lbl1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 215, 175));
        setMinimumSize(new java.awt.Dimension(900, 700));
        setPreferredSize(new java.awt.Dimension(935, 1050));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 1000));

        BaseTabbedPnl.setBackground(new java.awt.Color(243, 215, 175));
        BaseTabbedPnl.setPreferredSize(new java.awt.Dimension(930, 1000));

        LoginPnl.setBackground(new java.awt.Color(243, 215, 175));
        LoginPnl.setPreferredSize(new java.awt.Dimension(930, 1000));

        Title1lbl.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        Title1lbl.setForeground(new java.awt.Color(53, 119, 17));
        Title1lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1lbl.setText("<html> <body> <head> <u> Minesweeper <u> <head> <body> <html>");
        Title1lbl.setToolTipText("");

        LoginPasswordFld.setForeground(new java.awt.Color(204, 204, 204));
        LoginPasswordFld.setText("jPasswordField1");
        LoginPasswordFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginPasswordFldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginPasswordFldMouseExited(evt);
            }
        });
        LoginPasswordFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPasswordFldActionPerformed(evt);
            }
        });

        LoginUsernameFld.setForeground(new java.awt.Color(204, 204, 204));
        LoginUsernameFld.setText("Username");
        LoginUsernameFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginUsernameFldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LoginUsernameFldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LoginUsernameFldMouseExited(evt);
            }
        });
        LoginUsernameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginUsernameFldActionPerformed(evt);
            }
        });

        loginSubmitBtn.setBackground(new java.awt.Color(53, 119, 17));
        loginSubmitBtn.setForeground(new java.awt.Color(250, 250, 250));
        loginSubmitBtn.setText("Login");
        loginSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitBtnActionPerformed(evt);
            }
        });

        loginSubmitBtn1.setBackground(new java.awt.Color(53, 119, 17));
        loginSubmitBtn1.setForeground(new java.awt.Color(250, 250, 250));
        loginSubmitBtn1.setText("Create New");
        loginSubmitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginSubmitBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LoginPnlLayout = new javax.swing.GroupLayout(LoginPnl);
        LoginPnl.setLayout(LoginPnlLayout);
        LoginPnlLayout.setHorizontalGroup(
            LoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Title1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(LoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(LoginPnlLayout.createSequentialGroup()
                            .addComponent(loginSubmitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(LoginUsernameFld, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LoginPasswordFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(716, Short.MAX_VALUE))
        );
        LoginPnlLayout.setVerticalGroup(
            LoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginPnlLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Title1lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(LoginUsernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoginPasswordFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LoginPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginSubmitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(726, Short.MAX_VALUE))
        );

        BaseTabbedPnl.addTab("Login", LoginPnl);

        CreateNewPnl.setBackground(new java.awt.Color(243, 215, 175));

        CreateNewusernameFld.setForeground(new java.awt.Color(204, 204, 204));
        CreateNewusernameFld.setText("Username");
        CreateNewusernameFld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateNewusernameFldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CreateNewusernameFldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateNewusernameFldMouseExited(evt);
            }
        });
        CreateNewusernameFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewusernameFldActionPerformed(evt);
            }
        });

        CreateNewPswrdFld2.setForeground(new java.awt.Color(204, 204, 204));
        CreateNewPswrdFld2.setText("jPasswordField1");
        CreateNewPswrdFld2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateNewPswrdFld2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateNewPswrdFld2MouseExited(evt);
            }
        });
        CreateNewPswrdFld2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewPswrdFld2ActionPerformed(evt);
            }
        });

        CreateNewPswrdFld1.setForeground(new java.awt.Color(204, 204, 204));
        CreateNewPswrdFld1.setText("jPasswordField1");
        CreateNewPswrdFld1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateNewPswrdFld1MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CreateNewPswrdFld1MouseExited(evt);
            }
        });
        CreateNewPswrdFld1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewPswrdFld1ActionPerformed(evt);
            }
        });

        CreateNewSubmitBtn.setBackground(new java.awt.Color(53, 119, 17));
        CreateNewSubmitBtn.setForeground(new java.awt.Color(250, 250, 250));
        CreateNewSubmitBtn.setText("Submit");
        CreateNewSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewSubmitBtnActionPerformed(evt);
            }
        });

        CreateNewSubmitBtn1.setBackground(new java.awt.Color(53, 119, 17));
        CreateNewSubmitBtn1.setForeground(new java.awt.Color(250, 250, 250));
        CreateNewSubmitBtn1.setText("Back to Login");
        CreateNewSubmitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewSubmitBtn1ActionPerformed(evt);
            }
        });

        Title1lbl1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        Title1lbl1.setForeground(new java.awt.Color(53, 119, 17));
        Title1lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1lbl1.setText("<html> <body> <head> <u> Minesweeper <u> <head> <body> <html>");
        Title1lbl1.setToolTipText("");

        jLabel7.setText("<html><body> <h2 style = \"color:rgb(53,119,17);\">Password must contain: </h2>  <ul>  <li> A number </li>  <li> A special character: (@!”.#:~?) </li>  <li> 6 or more characters </li> </ul> </body></html>");

        javax.swing.GroupLayout CreateNewPnlLayout = new javax.swing.GroupLayout(CreateNewPnl);
        CreateNewPnl.setLayout(CreateNewPnlLayout);
        CreateNewPnlLayout.setHorizontalGroup(
            CreateNewPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateNewPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateNewPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateNewPnlLayout.createSequentialGroup()
                        .addGroup(CreateNewPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(CreateNewPnlLayout.createSequentialGroup()
                                .addComponent(CreateNewSubmitBtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CreateNewSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CreateNewusernameFld)
                            .addComponent(CreateNewPswrdFld1)
                            .addComponent(CreateNewPswrdFld2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Title1lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(477, Short.MAX_VALUE))
        );
        CreateNewPnlLayout.setVerticalGroup(
            CreateNewPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateNewPnlLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Title1lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(CreateNewPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CreateNewPnlLayout.createSequentialGroup()
                        .addComponent(CreateNewusernameFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CreateNewPswrdFld1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateNewPswrdFld2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CreateNewPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateNewSubmitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateNewSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(680, Short.MAX_VALUE))
        );

        BaseTabbedPnl.addTab("Create New", CreateNewPnl);

        HomePnl.setBackground(new java.awt.Color(243, 215, 175));

        EasySelectBtn.setBackground(new java.awt.Color(53, 119, 17));
        EasySelectBtn.setForeground(new java.awt.Color(250, 250, 250));
        EasySelectBtn.setText("Easy");
        EasySelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EasySelectBtnActionPerformed(evt);
            }
        });

        MediumSelectBtn.setBackground(new java.awt.Color(53, 119, 17));
        MediumSelectBtn.setForeground(new java.awt.Color(250, 250, 250));
        MediumSelectBtn.setText("Medium");
        MediumSelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MediumSelectBtnActionPerformed(evt);
            }
        });

        HardSelectBtn.setBackground(new java.awt.Color(53, 119, 17));
        HardSelectBtn.setForeground(new java.awt.Color(250, 250, 250));
        HardSelectBtn.setText("Hard");
        HardSelectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HardSelectBtnActionPerformed(evt);
            }
        });

        homeHelpbtn.setBackground(new java.awt.Color(53, 119, 17));
        homeHelpbtn.setForeground(new java.awt.Color(250, 250, 250));
        homeHelpbtn.setText("Help");
        homeHelpbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeHelpbtnActionPerformed(evt);
            }
        });

        statisticsBtn.setBackground(new java.awt.Color(53, 119, 17));
        statisticsBtn.setForeground(new java.awt.Color(250, 250, 250));
        statisticsBtn.setText("Statistics");
        statisticsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsBtnActionPerformed(evt);
            }
        });

        homeUsernamefld.setEditable(false);
        homeUsernamefld.setText("Username");

        Title1lbl2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        Title1lbl2.setForeground(new java.awt.Color(53, 119, 17));
        Title1lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1lbl2.setText("<html> <body> <head> <u> Minesweeper <u> <head> <body> <html>");
        Title1lbl2.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel2.setText("Select difficulty:");

        exitButton.setBackground(new java.awt.Color(53, 119, 17));
        exitButton.setForeground(new java.awt.Color(250, 250, 250));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("10x10");

        jLabel9.setText("15 Mines");

        jLabel10.setText("15x15");

        jLabel11.setText("30 Mines");

        jLabel12.setText("20x20");

        jLabel13.setText("50 Mines");

        javax.swing.GroupLayout HomePnlLayout = new javax.swing.GroupLayout(HomePnl);
        HomePnl.setLayout(HomePnlLayout);
        HomePnlLayout.setHorizontalGroup(
            HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Title1lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePnlLayout.createSequentialGroup()
                        .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(HomePnlLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9))
                            .addComponent(EasySelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(HomePnlLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addComponent(MediumSelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HardSelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(HomePnlLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(homeUsernamefld, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(statisticsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(homeHelpbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(353, 353, 353))
        );
        HomePnlLayout.setVerticalGroup(
            HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePnlLayout.createSequentialGroup()
                        .addComponent(homeUsernamefld, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statisticsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(homeHelpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePnlLayout.createSequentialGroup()
                        .addComponent(Title1lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EasySelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MediumSelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HardSelectBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13))
                            .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGroup(HomePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9)))))
                .addContainerGap(576, Short.MAX_VALUE))
        );

        BaseTabbedPnl.addTab("Home", HomePnl);

        GameBasePnl.setBackground(new java.awt.Color(243, 215, 175));
        GameBasePnl.setPreferredSize(new java.awt.Dimension(900, 900));

        GameInfoPnl.setBackground(new java.awt.Color(243, 215, 175));
        GameInfoPnl.setPreferredSize(new java.awt.Dimension(900, 100));

        helpGameBtn.setBackground(new java.awt.Color(53, 119, 17));
        helpGameBtn.setForeground(new java.awt.Color(250, 250, 250));
        helpGameBtn.setText("Help");
        helpGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpGameBtnActionPerformed(evt);
            }
        });

        quitBtn1.setBackground(new java.awt.Color(53, 119, 17));
        quitBtn1.setForeground(new java.awt.Color(250, 250, 250));
        quitBtn1.setText("Quit");
        quitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtn1ActionPerformed(evt);
            }
        });

        flagNumberfld.setEditable(false);
        flagNumberfld.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        flagNumberfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flagNumberfldActionPerformed(evt);
            }
        });

        timerLbl.setEditable(false);
        timerLbl.setText("Time left or current elapsed time:");
        timerLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerLblActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Flags left:");

        javax.swing.GroupLayout GameInfoPnlLayout = new javax.swing.GroupLayout(GameInfoPnl);
        GameInfoPnl.setLayout(GameInfoPnlLayout);
        GameInfoPnlLayout.setHorizontalGroup(
            GameInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameInfoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helpGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(timerLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(flagNumberfld, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        GameInfoPnlLayout.setVerticalGroup(
            GameInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameInfoPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GameInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GameInfoPnlLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(timerLbl))
                    .addGroup(GameInfoPnlLayout.createSequentialGroup()
                        .addGroup(GameInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(GameInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(flagNumberfld, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(GameInfoPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(helpGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        GameGridPnl.setBackground(new java.awt.Color(243, 215, 175));
        GameGridPnl.setPreferredSize(new java.awt.Dimension(900, 900));

        javax.swing.GroupLayout GameGridPnlLayout = new javax.swing.GroupLayout(GameGridPnl);
        GameGridPnl.setLayout(GameGridPnlLayout);
        GameGridPnlLayout.setHorizontalGroup(
            GameGridPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        GameGridPnlLayout.setVerticalGroup(
            GameGridPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 866, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout GameBasePnlLayout = new javax.swing.GroupLayout(GameBasePnl);
        GameBasePnl.setLayout(GameBasePnlLayout);
        GameBasePnlLayout.setHorizontalGroup(
            GameBasePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GameInfoPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
            .addComponent(GameGridPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        GameBasePnlLayout.setVerticalGroup(
            GameBasePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameBasePnlLayout.createSequentialGroup()
                .addComponent(GameInfoPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GameGridPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE))
        );

        BaseTabbedPnl.addTab("Game", GameBasePnl);

        HelpPnl.setBackground(new java.awt.Color(243, 215, 175));

        Title1lbl3.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        Title1lbl3.setForeground(new java.awt.Color(53, 119, 17));
        Title1lbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1lbl3.setText("<html> <body> <head> <u> Minesweeper <u> <head> <body> <html>");
        Title1lbl3.setToolTipText("");

        helpHomebtn.setBackground(new java.awt.Color(53, 119, 17));
        helpHomebtn.setForeground(new java.awt.Color(250, 250, 250));
        helpHomebtn.setText("Quit Game");
        helpHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpHomebtnActionPerformed(evt);
            }
        });

        backToGamebtn.setBackground(new java.awt.Color(53, 119, 17));
        backToGamebtn.setForeground(new java.awt.Color(250, 250, 250));
        backToGamebtn.setText("Back to Game ");
        backToGamebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToGamebtnActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Upon your first click, an area on the grid will be cleared (blue), this will reveal numbers in the tiles that are adjacent to the uncleared tiles (green).  \nEach number represents the number of mines around that tile (up, left, down, right and the four diagonal corners).  \nUsing this, you are to deduce the positions of all mines in the grid.  \n-----------------------------------\nThe easy difficulty has 15 mines.  \nThe medium difficulty has 30 mines.  \nThe hard difficulty has 50 mines.  \n-----------------------------------\nYou should right click on tiles that you suspect contain a mine to flag the tile.  You have as many flags as there are mines. You should left click on all other tiles to clear them.  Once you have cleared all of the tiles that do not contain mines the game will end, and you have won.     \n\nTip: If you are stuck, look for 1s on the grid. These are very useful at identifying mines.   Corner tiles with a number 1 next to them can easily tell you the position of a mine.\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout HelpPnlLayout = new javax.swing.GroupLayout(HelpPnl);
        HelpPnl.setLayout(HelpPnlLayout);
        HelpPnlLayout.setHorizontalGroup(
            HelpPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPnlLayout.createSequentialGroup()
                .addGroup(HelpPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title1lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HelpPnlLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(HelpPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(backToGamebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(helpHomebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        HelpPnlLayout.setVerticalGroup(
            HelpPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPnlLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Title1lbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(HelpPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPnlLayout.createSequentialGroup()
                        .addComponent(helpHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backToGamebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(385, Short.MAX_VALUE))
        );

        BaseTabbedPnl.addTab("Help", HelpPnl);

        UserStatsPnl.setBackground(new java.awt.Color(243, 215, 175));
        UserStatsPnl.setPreferredSize(new java.awt.Dimension(900, 900));

        statisticsUsernamefld.setEditable(false);
        statisticsUsernamefld.setText("Username");

        winLossfld.setEditable(false);
        winLossfld.setText("Games Played etc.");

        Title1lbl4.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        Title1lbl4.setForeground(new java.awt.Color(53, 119, 17));
        Title1lbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title1lbl4.setText("<html> <body> <head> <u> Minesweeper <u> <head> <body> <html>");
        Title1lbl4.setToolTipText("");

        statisticsHomebtn.setBackground(new java.awt.Color(53, 119, 17));
        statisticsHomebtn.setForeground(new java.awt.Color(250, 250, 250));
        statisticsHomebtn.setText("Home");
        statisticsHomebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsHomebtnActionPerformed(evt);
            }
        });

        tilesClearedfld.setEditable(false);
        tilesClearedfld.setText("Games Won");
        tilesClearedfld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilesClearedfldActionPerformed(evt);
            }
        });

        gamesWonfld.setEditable(false);
        gamesWonfld.setText("Total Mines Cleared");

        gamesPlayedfdl.setEditable(false);
        gamesPlayedfdl.setText("Win/Loss");

        jLabel3.setText("Number of Games Won:");

        jLabel4.setText("Win-Loss Ratio: ");

        jLabel5.setText("Career Tiles Cleared:");

        jLabel6.setText("Number of Games Played:");

        javax.swing.GroupLayout UserStatsPnlLayout = new javax.swing.GroupLayout(UserStatsPnl);
        UserStatsPnl.setLayout(UserStatsPnlLayout);
        UserStatsPnlLayout.setHorizontalGroup(
            UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserStatsPnlLayout.createSequentialGroup()
                .addGroup(UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserStatsPnlLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statisticsUsernamefld, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(UserStatsPnlLayout.createSequentialGroup()
                                .addGroup(UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gamesPlayedfdl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gamesWonfld, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(statisticsHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(winLossfld, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tilesClearedfld, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addGroup(UserStatsPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Title1lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(518, Short.MAX_VALUE))
        );
        UserStatsPnlLayout.setVerticalGroup(
            UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserStatsPnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Title1lbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(statisticsUsernamefld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamesPlayedfdl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(winLossfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserStatsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamesWonfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tilesClearedfld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(statisticsHomebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(674, Short.MAX_VALUE))
        );

        BaseTabbedPnl.addTab("Statistics", UserStatsPnl);

        WinPnl.setBackground(new java.awt.Color(243, 215, 175));

        Title2Lbl2.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        Title2Lbl2.setForeground(new java.awt.Color(53, 119, 17));
        Title2Lbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2Lbl2.setText("<html> <body> <head> You Win!<head> <body> <html>");
        Title2Lbl2.setToolTipText("");

        playAgainWinbtn.setBackground(new java.awt.Color(53, 119, 17));
        playAgainWinbtn.setForeground(new java.awt.Color(250, 250, 250));
        playAgainWinbtn.setText("Home");
        playAgainWinbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainWinbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WinPnlLayout = new javax.swing.GroupLayout(WinPnl);
        WinPnl.setLayout(WinPnlLayout);
        WinPnlLayout.setHorizontalGroup(
            WinPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WinPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Title2Lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playAgainWinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(784, Short.MAX_VALUE))
        );
        WinPnlLayout.setVerticalGroup(
            WinPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinPnlLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Title2Lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(playAgainWinbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(823, Short.MAX_VALUE))
        );

        BaseTabbedPnl.addTab("WinScreen", WinPnl);

        LossPnl.setBackground(new java.awt.Color(243, 215, 175));

        Title2Lbl1.setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        Title2Lbl1.setForeground(new java.awt.Color(53, 119, 17));
        Title2Lbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title2Lbl1.setText("<html> <body> <head> You LOSE!<head> <body> <html>");
        Title2Lbl1.setToolTipText("");

        jButton1.setBackground(new java.awt.Color(53, 119, 17));
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LossPnlLayout = new javax.swing.GroupLayout(LossPnl);
        LossPnl.setLayout(LossPnlLayout);
        LossPnlLayout.setHorizontalGroup(
            LossPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LossPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LossPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Title2Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(778, Short.MAX_VALUE))
        );
        LossPnlLayout.setVerticalGroup(
            LossPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LossPnlLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Title2Lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(810, Short.MAX_VALUE))
        );

        BaseTabbedPnl.addTab("LossScreen", LossPnl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BaseTabbedPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BaseTabbedPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HardSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HardSelectBtnActionPerformed
        rows = 20;
        columns = 20;
        totalMineCount = 50;
        buttons_cleared = new boolean[20][20];
        BaseTabbedPnl.setSelectedIndex(3);
        flagNumberfld.setText(Integer.toString(totalMineCount - flagged));
        try {
            generateGrid();
        } catch (IOException ex) {
            Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_HardSelectBtnActionPerformed

    private void MediumSelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MediumSelectBtnActionPerformed
        rows = 15;
        columns = 15;
        totalMineCount = 30;
        buttons_cleared = new boolean[15][15];
        BaseTabbedPnl.setSelectedIndex(3);
        flagNumberfld.setText(Integer.toString(totalMineCount - flagged));
        try {
            generateGrid();
        } catch (IOException ex) {
            Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MediumSelectBtnActionPerformed

    private void EasySelectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EasySelectBtnActionPerformed
        rows = 10;
        columns = 10;
        totalMineCount = 15;
        buttons_cleared = new boolean[10][10];
        BaseTabbedPnl.setSelectedIndex(3);
        flagNumberfld.setText(Integer.toString(totalMineCount - flagged));
        try {
            generateGrid();
        } catch (IOException ex) {
            Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EasySelectBtnActionPerformed

    private void loginSubmitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitBtn1ActionPerformed
        BaseTabbedPnl.setSelectedIndex(1);
    }//GEN-LAST:event_loginSubmitBtn1ActionPerformed

    private void loginSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginSubmitBtnActionPerformed
        //get the username and password from the login fields
        String username = LoginUsernameFld.getText();
        char[] pswrdChar = LoginPasswordFld.getPassword();
        /*Convert password character array to a string*/
        String password = "";
        for (char c : pswrdChar) {
            password = password + c;
        }
        try {
            //If the entered details match a pair of details in a text file
            if (checkDetails(username, password)) {
                homeUsernamefld.setText(username);
                statisticsUsernamefld.setText(username);
                accountName = username;
                BaseTabbedPnl.setSelectedIndex(2);
            } else {
                LoginUsernameFld.setForeground(Color.red);
                LoginUsernameFld.setText("Incorrect Username or Password");
                LoginPasswordFld.setText("");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_loginSubmitBtnActionPerformed

    private void LoginUsernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginUsernameFldActionPerformed
        //TODO add your handling code here:
    }//GEN-LAST:event_LoginUsernameFldActionPerformed

    private void LoginUsernameFldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginUsernameFldMouseExited

    }//GEN-LAST:event_LoginUsernameFldMouseExited

    private void LoginUsernameFldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginUsernameFldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginUsernameFldMouseEntered

    private void LoginUsernameFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginUsernameFldMouseClicked
        LoginUsernameFld.setText("");
        LoginUsernameFld.setForeground(Color.BLACK);
    }//GEN-LAST:event_LoginUsernameFldMouseClicked

    private void LoginPasswordFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPasswordFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginPasswordFldActionPerformed

    private void LoginPasswordFldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPasswordFldMouseExited

    }//GEN-LAST:event_LoginPasswordFldMouseExited

    private void LoginPasswordFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginPasswordFldMouseClicked
        LoginPasswordFld.setText("");
        LoginPasswordFld.setForeground(Color.BLACK);
    }//GEN-LAST:event_LoginPasswordFldMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BaseTabbedPnl.setSelectedIndex(2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void homeHelpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeHelpbtnActionPerformed
        BaseTabbedPnl.setSelectedIndex(4);
    }//GEN-LAST:event_homeHelpbtnActionPerformed

    private void flagNumberfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flagNumberfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flagNumberfldActionPerformed

    private void timerLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerLblActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timerLblActionPerformed

    private void statisticsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsBtnActionPerformed
        //change the user visible panel to the statistics page
        BaseTabbedPnl.setSelectedIndex(5);
        //Populate each of the statistics fields
        gamesPlayedfdl.setText(getStatistic(2));
        gamesWonfld.setText(getStatistic(3));
        tilesClearedfld.setText(getStatistic(4));
        //Call function to calculate and populate winLoss ratio 
        populateWinLoss();
    }//GEN-LAST:event_statisticsBtnActionPerformed

    private void quitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtn1ActionPerformed
        game_in_progress = false;
        flagged = 0;
        BaseTabbedPnl.setSelectedIndex(2);
    }//GEN-LAST:event_quitBtn1ActionPerformed

    private void helpGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpGameBtnActionPerformed
        BaseTabbedPnl.setSelectedIndex(4);
    }//GEN-LAST:event_helpGameBtnActionPerformed

    private void helpHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpHomebtnActionPerformed
        flagged = 0;
        game_in_progress = false;
        BaseTabbedPnl.setSelectedIndex(2);
    }//GEN-LAST:event_helpHomebtnActionPerformed

    private void playAgainWinbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainWinbtnActionPerformed
        BaseTabbedPnl.setSelectedIndex(2);
    }//GEN-LAST:event_playAgainWinbtnActionPerformed

    private void backToGamebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToGamebtnActionPerformed
        BaseTabbedPnl.setSelectedIndex(3);
    }//GEN-LAST:event_backToGamebtnActionPerformed

    private void tilesClearedfldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilesClearedfldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tilesClearedfldActionPerformed

    private void statisticsHomebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statisticsHomebtnActionPerformed
        BaseTabbedPnl.setSelectedIndex(2);
    }//GEN-LAST:event_statisticsHomebtnActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void CreateNewSubmitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewSubmitBtn1ActionPerformed
        BaseTabbedPnl.setSelectedIndex(0);
    }//GEN-LAST:event_CreateNewSubmitBtn1ActionPerformed

    private void CreateNewSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewSubmitBtnActionPerformed
        //get the username and pasword
        String username = CreateNewusernameFld.getText();

        //get first password and convert from character array to string
        char[] pswrdChar = CreateNewPswrdFld1.getPassword();
        String password1 = "";
        for (char c : pswrdChar) {
            password1 = password1 + c;
        }

        //Get the second password and convert from character array to a string
        pswrdChar = CreateNewPswrdFld2.getPassword();
        String password2 = "";
        for (char c : pswrdChar) {
            password2 = password2 + c;
        }
        /*Checks on inputs:
        - Check that the two provided passwords match
        - Check that the provided username has not already been used
        - Check that the password is not empty
        - Check that the username is not empty
        */
        if (password1.equals(password2) && !userExists(username)
            && !(password1.trim()).equals("") && !(username.trim()).equals("") && passwordFormat(password2)) {
            try {
                //if checks successful, store details to a new file
                writeNewUser(username, password1);
            } catch (IOException ex) {
                Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Account creation successful, forward the user to the game panel
            homeUsernamefld.setText(username);
            statisticsUsernamefld.setText(username);
            accountName = username;
            BaseTabbedPnl.setSelectedIndex(2);
            try {
                setDefaultStatistics();
            } catch (IOException ex) {
                Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            //if the checks fail, display error message
            CreateNewusernameFld.setForeground(Color.red);
            CreateNewusernameFld.setText("Failed account creation, try again");
            CreateNewPswrdFld1.setText("");
            CreateNewPswrdFld2.setText("");
        }
    }//GEN-LAST:event_CreateNewSubmitBtnActionPerformed

    private void CreateNewPswrdFld1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewPswrdFld1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewPswrdFld1ActionPerformed

    private void CreateNewPswrdFld1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateNewPswrdFld1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewPswrdFld1MouseExited

    private void CreateNewPswrdFld1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateNewPswrdFld1MouseClicked
        CreateNewPswrdFld1.setText("");
        CreateNewPswrdFld1.setForeground(Color.BLACK);
    }//GEN-LAST:event_CreateNewPswrdFld1MouseClicked

    private void CreateNewPswrdFld2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewPswrdFld2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewPswrdFld2ActionPerformed

    private void CreateNewPswrdFld2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateNewPswrdFld2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewPswrdFld2MouseExited

    private void CreateNewPswrdFld2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateNewPswrdFld2MouseClicked
        CreateNewPswrdFld2.setText("");
        CreateNewPswrdFld2.setForeground(Color.BLACK);
    }//GEN-LAST:event_CreateNewPswrdFld2MouseClicked

    private void CreateNewusernameFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewusernameFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewusernameFldActionPerformed

    private void CreateNewusernameFldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateNewusernameFldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewusernameFldMouseExited

    private void CreateNewusernameFldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateNewusernameFldMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewusernameFldMouseEntered

    private void CreateNewusernameFldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateNewusernameFldMouseClicked
        CreateNewusernameFld.setText("");
        CreateNewusernameFld.setForeground(Color.BLACK);
    }//GEN-LAST:event_CreateNewusernameFldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabbedProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabbedProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabbedProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabbedProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabbedProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BaseTabbedPnl;
    private javax.swing.JPanel CreateNewPnl;
    private javax.swing.JPasswordField CreateNewPswrdFld1;
    private javax.swing.JPasswordField CreateNewPswrdFld2;
    private javax.swing.JToggleButton CreateNewSubmitBtn;
    private javax.swing.JToggleButton CreateNewSubmitBtn1;
    private javax.swing.JTextField CreateNewusernameFld;
    private javax.swing.JButton EasySelectBtn;
    private javax.swing.JPanel GameBasePnl;
    private javax.swing.JPanel GameGridPnl;
    private javax.swing.JPanel GameInfoPnl;
    private javax.swing.JButton HardSelectBtn;
    private javax.swing.JPanel HelpPnl;
    private javax.swing.JPanel HomePnl;
    private javax.swing.JPasswordField LoginPasswordFld;
    private javax.swing.JPanel LoginPnl;
    private javax.swing.JTextField LoginUsernameFld;
    private javax.swing.JPanel LossPnl;
    private javax.swing.JButton MediumSelectBtn;
    private javax.swing.JLabel Title1lbl;
    private javax.swing.JLabel Title1lbl1;
    private javax.swing.JLabel Title1lbl2;
    private javax.swing.JLabel Title1lbl3;
    private javax.swing.JLabel Title1lbl4;
    private javax.swing.JLabel Title2Lbl1;
    private javax.swing.JLabel Title2Lbl2;
    private javax.swing.JPanel UserStatsPnl;
    private javax.swing.JPanel WinPnl;
    private javax.swing.JButton backToGamebtn;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField flagNumberfld;
    private javax.swing.JTextField gamesPlayedfdl;
    private javax.swing.JTextField gamesWonfld;
    private javax.swing.JButton helpGameBtn;
    private javax.swing.JButton helpHomebtn;
    private javax.swing.JButton homeHelpbtn;
    private javax.swing.JTextField homeUsernamefld;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton loginSubmitBtn;
    private javax.swing.JToggleButton loginSubmitBtn1;
    private javax.swing.JButton playAgainWinbtn;
    private javax.swing.JButton quitBtn1;
    private javax.swing.JButton statisticsBtn;
    private javax.swing.JButton statisticsHomebtn;
    private javax.swing.JTextField statisticsUsernamefld;
    private javax.swing.JTextField tilesClearedfld;
    private javax.swing.JTextField timerLbl;
    private javax.swing.JTextField winLossfld;
    // End of variables declaration//GEN-END:variables

    private void generateGrid() throws IOException {
        //clear the grid from the previous game
        GameGridPnl.removeAll();
        GameGridPnl.setLayout(new GridLayout(rows, columns));
        GameGridPnl.setSize(400, 400);
        //Add the buttons to the panel's gridLayout 
        buttons = new JButton[rows][columns];
        //Repeat rows*columns number of times 
        for (int r = 0; r < rows; r++) {
            for (int c = 0; c < columns; c++) {
                JButton btn = new JButton();
                /*row and col are temporary variables needed to use the values 
                of r and c within the action listener subroutine */
                int row = r;
                int col = c;
                //add an action listener for each button that is created 
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        if (!btn.getText().equals("⚑")) {
                            //If this is the first button clicked, start the game
                            if (game_in_progress == false) {
                                placeMines(row, col);
                                gridClear(row, col);
                                game_in_progress = true;
                            }
                            //check to see if this location has a mine 
                            if (buttons_As_Mines[row][col] == -1) {
                                gameLoss();
                            } else {
                                gridClear(row, col);
                                //Check whether the user has cleared the grid fully
                                gameSuccessful();
                            }
                            //Show the relevant mine numbers to the user
                            revealGridNumbers();
                        }
                    }

                });
                btn.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent m) {
                        if (SwingUtilities.isRightMouseButton(m)) {
                            if (btn.getText().equals("")) {
                                btn.setForeground(Color.RED);
                                btn.setText("⚑");
                                flagged = flagged + 1;
                            } else if (btn.getText().equals("⚑")) {
                                btn.setForeground(Color.red);
                                btn.setText("?");
                                flagged = flagged - 1;
                            }else{
                                btn.setForeground(Color.BLACK);
                                btn.setText("");
                            }
                            flagNumberfld.setText(Integer.toString(totalMineCount - flagged));
                        }
                    }
                });
                btn.setBackground(Color.GREEN);//Defualt colour
                //Add the generated button to the button array and the panel 
                buttons[r][c] = btn;
                GameGridPnl.add(btn);
                btn.setFont(new Font("Ariel", Font.PLAIN, 22));
                btn.setText("");
            }
        }
    }

//Subroutine to store the username and password
    private void writeNewUser(String username, String password) throws IOException {
        String filePath = "P:\\Component 3\\ProjectTest\\User Files\\" + username + ".txt";
        //Create new file to contain this users' details with username as name
        File file = new File(filePath);
        //Write the password to the first line
        try ( //Initialise filewriter
                FileWriter fileWrite = new FileWriter(file)) {
            //Write the password to the first line
            fileWrite.write(password);
        }
    }

    /*subroutine to return true or false, representing whether the username and 
    password match*/
    private boolean checkDetails(String username, String password) throws FileNotFoundException {
        //Declare the folder being accessed and add its files to a list
        File folder = new File("P:\\Component 3\\ProjectTest\\User Files");
        File[] listOfFiles = folder.listFiles();
        //iterate through all files in the folder
        for (File file : listOfFiles) {
            //If this username has a file, move on to check the password
            if (file.getName().equals(username + ".txt")) {
                //declare scanner for this file
                Scanner read = new Scanner(file);
                /*If the password matches the one stored in the text file, the
                below statment will return true.
                 */
                return read.nextLine().equals(password);
            }
        }
        return false;
    }

    //subroutine to check that a provided username is unique .
    //returns true if the user exists already, returns false if not 
    private boolean userExists(String username) {
        //Declare the folder being accessed and add its files to a list
        File folder = new File("P:\\Component 3\\ProjectTest\\User Files");
        File[] listOfFiles = folder.listFiles();
        //iterate through all files in the folder
        for (File file : listOfFiles) {
            //if there is already a file created for this user, return true
            if (file.getName().equals(username + ".txt")) {
                return true;
            }
        }
        return false;
    }

    //subroutine to update buttonsAsMines to contain the position of mines
    private void placeMines(int initialRow, int initialCol) {
        //Initialisation 
        int generatedR;
        int generatedC;
        int mines = 0;
        buttons_As_Mines = new int[rows][columns];
        /*loop to iterate while the number of mines placed in the 2D array for 
        the grid is less than totalMineCount*/
        while (mines < totalMineCount) {
            //Generate a random x and y coordinate
            generatedR = (int) (Math.random() * rows);
            generatedC = (int) (Math.random() * columns);
            /*if this position does not already have a mine and is not the initial 
            index clicked by the user*/
            if (buttons_As_Mines[generatedR][generatedC] != -1
                    && (generatedR != initialRow || generatedC != initialCol) //centre
                    && (generatedR != initialRow - 1 || generatedC != initialCol - 1) //above left
                    && (generatedR != initialRow - 1 || generatedC != initialCol) //above 
                    && (generatedR != initialRow - 1 || generatedC != initialCol + 1) //above right
                    && (generatedR != initialRow || generatedC != initialCol - 1) //left
                    && (generatedR != initialRow || generatedC != initialCol + 1) //right
                    && (generatedR != initialRow + 1 || generatedC != initialCol - 1)//below left
                    && (generatedR != initialRow + 1 || generatedC != initialCol) //below
                    && (generatedR != initialRow + 1 || generatedC != initialCol + 1) //below right
                    ) {
                buttons_As_Mines[generatedR][generatedC] = -1;
                //increment mines 
                mines += 1;
                //increment adjacent mine numbers 
                updateMineNumbers(generatedR, generatedC);
            }
        }
    }

    //subroutine to increment by 1, the adjacent grid spaces to a given index
    private void updateMineNumbers(int row, int column) {
        /*for each index, the index must be checked to see that it is in the 
        bounds of the current grid and that it does not also contain a mine*/
        //increment grid space to the left
        if (inBounds(row, column - 1) && buttons_As_Mines[row][column - 1] != -1) {
            buttons_As_Mines[row][column - 1] += 1;
        }
        //increment grid space to the right
        if (inBounds(row, column + 1) && buttons_As_Mines[row][column + 1] != -1) {
            buttons_As_Mines[row][column + 1] += 1;
        }
        //increment button directly above & its adjacent buttons left and right:
        /*
        loop iterates from left to middle to right 
         */
        for (int i = -1; i < 2; i++) {
            if (inBounds(row - 1, column + i) && buttons_As_Mines[row - 1][column + i] != -1) {
                buttons_As_Mines[row - 1][column + i] += 1;
            }
        }
        //increment button directly below & its adjacent buttons left and right
        for (int i = -1; i < 2; i++) {
            if (inBounds(row + 1, column + i) && buttons_As_Mines[row + 1][column + i] != -1) {
                buttons_As_Mines[row + 1][column + i] += 1;
            }
        }
    }

    //checks if the given index is within the bounds of the grid
    //returns true if the index exists and false if not
    private boolean inBounds(int r, int c) {
        if ((r <= rows - 1 && r >= 0) && (c <= columns - 1 && c >= 0)) {
            return true;
        }
        return false;
    }

    private void gridClear(int r, int c) {
        //set current mine to clear
        buttons_cleared[r][c] = true;
        buttons[r][c].setBackground(Color.cyan);
        if (buttons_As_Mines[r][c] == 0) {

            //Check Above
            /*check that the index is in bounds, that the index does not contain a mine,
            that the index is not already cleared and that the index has 0 adjacent mines*/
            if (inBounds(r - 1, c) && buttons_cleared[r - 1][c] != true) {
                //set the index to clear and make this change visible to the user 
                buttons_cleared[r - 1][c] = true;
                buttons[r - 1][c].setBackground(Color.cyan);
                //call the fucntion recursively
                gridClear(r - 1, c);
            }
            //Check above left
            if (inBounds(r - 1, c - 1) && buttons_cleared[r - 1][c - 1] != true) {
                buttons_cleared[r - 1][c - 1] = true;
                buttons[r + - 1][c - 1].setBackground(Color.cyan);
                gridClear(r - 1, c - 1);
            }
            //Check above right
            if (inBounds(r - 1, c + 1) && buttons_cleared[r - 1][c + 1] != true) {
                buttons_cleared[r - 1][c + 1] = true;
                buttons[r - 1][c + 1].setBackground(Color.cyan);
                gridClear(r - 1, c + 1);
            }
            //Check Below
            if (inBounds(r + 1, c) && buttons_cleared[r + 1][c] != true) {
                buttons_cleared[r + 1][c] = true;
                buttons[r + 1][c].setBackground(Color.cyan);
                gridClear(r + 1, c);
            }
            //Check below left
            if (inBounds(r + 1, c - 1) && buttons_cleared[r + 1][c - 1] != true) {
                buttons_cleared[r + 1][c - 1] = true;
                buttons[r + 1][c - 1].setBackground(Color.cyan);
                gridClear(r + 1, c - 1);
            }
            //Check below right
            if (inBounds(r + 1, c + 1) && buttons_cleared[r + 1][c + 1] != true) {
                buttons_cleared[r + 1][c + 1] = true;
                buttons[r + 1][c + 1].setBackground(Color.cyan);
                gridClear(r + 1, c + 1);
            }
            //Check Left 
            if (inBounds(r, c - 1) && buttons_cleared[r][c - 1] != true) {
                buttons_cleared[r][c - 1] = true;
                buttons[r][c - 1].setBackground(Color.cyan);
                gridClear(r, c - 1);
            }
            //Check Right
            if (inBounds(r, c + 1) && buttons_cleared[r][c + 1] != true) {
                buttons_cleared[r][c + 1] = true;
                buttons[r][c + 1].setBackground(Color.cyan);
                gridClear(r, c + 1);
            }
        }
    }

    private void gameLoss() {
        game_in_progress = false;
        flagged = 0;
        //select loss screen 
        BaseTabbedPnl.setSelectedIndex(7);
        GameGridPnl.removeAll();
        try {
            //increment games played
            incrementStatistic(1);
        } catch (IOException ex) {
            Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    //subroutine to check if the grid has been fully cleared
    private void gameSuccessful() {
        //count is the number of cleared spaces in the grid 
        int count = 0;
        //total is the number of spaces in the grid (No. of rows * No. of cols)
        int total = buttons_cleared.length * buttons_cleared[0].length;
        //iterate through the indexes in the grid 
        for (int row = 0; row < buttons_cleared.length; row++) {
            for (int column = 0; column < buttons_cleared[row].length; column++) {
                //if a grid space is clear, increment count
                if (buttons_cleared[row][column] == true) {
                    count = count + 1;
                }
            }
        }
        //if the user has cleared all non-mine spaces
        if (total - count == totalMineCount) {
            game_in_progress = false;
            flagged = 0;
            try {
                //increment win statistic
                incrementStatistic(3);
            } catch (IOException ex) {
                Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
            }
            //select win screen
            BaseTabbedPnl.setSelectedIndex(6);
        }
    }

    //subroutine to update the numbers in the grid
    /*if a tile displays a number but there is not an uncleared tile in the 
    surrounding 8 tiles then the number should be removed */
    //if there is an uncleared tile, show the number 
    private void revealGridNumbers() {
        //iterate through each button in the grid
        //the index of each button is given by [rows][columns]
        for (int rows = 0; rows < buttons.length; rows++) {
            for (int columns = 0; columns < buttons[rows].length; columns++) {
                //if any of of the contained statments are true the if will execute 
                /*
                If a tile is clear and any of the 8 tiles around it are not clear 
                then the number of mines around it should be displayed  
                 */
                //if a tile is cleared, move on to check the surrounding tiles 
                if (buttons_cleared[rows][columns] == true) {

                    if ((inBounds(rows - 1, columns - 1) && buttons_cleared[rows - 1][columns - 1] == false)
                            ||//above left
                            (inBounds(rows - 1, columns) && buttons_cleared[rows - 1][columns] == false)
                            ||//above 
                            (inBounds(rows - 1, columns + 1) && buttons_cleared[rows - 1][columns + 1] == false)
                            ||//above right
                            (inBounds(rows, columns - 1) && buttons_cleared[rows][columns - 1] == false)
                            ||//left
                            (inBounds(rows, columns + 1) && buttons_cleared[rows][columns + 1] == false)
                            ||//right
                            (inBounds(rows + 1, columns - 1) && buttons_cleared[rows + 1][columns - 1] == false)
                            ||//below left
                            (inBounds(rows + 1, columns) && buttons_cleared[rows + 1][columns] == false)
                            ||//below middle
                            (inBounds(rows + 1, columns + 1) && buttons_cleared[rows + 1][columns + 1] == false) //below right
                            ) {
                        buttons[rows][columns].setText(Integer.toString(buttons_As_Mines[rows][columns]));
                    }
                }
            }
        }
    }

    //to complete/change based on design
    public void incrementStatistic(int lineNum) throws FileNotFoundException, IOException {
        //declare variables for the specified statistic and convert to an integer
        String statisticLine = getStatistic(lineNum);
        int integerStatistic = Integer.valueOf(statisticLine);
        //increment the number of the specified statistic
        integerStatistic = integerStatistic + 1;
        //convert integer value back to string
        statisticLine = Integer.toString(integerStatistic);
        //write the new number of the specified statistic 
        String filePath = "P:\\Component 3\\ProjectTest\\User Files\\" + accountName + ".txt";
        //Create new file to contain this users' details with username as name
        File file = new File(filePath);

        //declare a list of all the lines in the file
        List<String> lines = Files.readAllLines(file.toPath());
        //change list element at index 1 to the new value of gamesPlayed
        lines.set(lineNum, statisticLine);
        //write the file using the updated list
        Files.write(file.toPath(), lines);
    }

    public boolean passwordFormat(String password) {
        //define the regex of the password (its conditions for validity)
        String regex = "^(?=.*[0-9])(?=.*[@£#$%^!&-+=()]).{6,}$";
        //complie the regex and define the password
        Pattern p = Pattern.compile(regex);
        Matcher m = p.matcher(password);
        //Check if the password fits these criteria and return the result
        return m.matches();
    }

    public String getStatistic(int lineNum) {
        //declare statistics variable as null
        String statistic = "";
        String username = accountName;
        int line = 0;
        //convert lineNum to 0th indexing 
        lineNum = lineNum - 1;
        //Declare the folder being accessed and add its files to a list
        File folder = new File("P:\\Component 3\\ProjectTest\\User Files");
        File[] listOfFiles = folder.listFiles();
        //iterate through all files in the folder
        for (File file : listOfFiles) {
            //If the correct file is found
            if (file.getName().equals(username + ".txt")) {
                FileReader fileRead = null;
                try {
                    //declare scanner to read from this file
                    fileRead = new FileReader(file);
                    BufferedReader reader = new BufferedReader(fileRead);
                    while (line <= lineNum) {
                        statistic = reader.readLine();
                        line = line + 1;
                    }
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    try {
                        fileRead.close();
                    } catch (IOException ex) {
                        Logger.getLogger(TabbedProject.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        return statistic;
    }

    public void populateWinLoss() {
        //declare float variables for the number of games played and won
        float gamesPlayed = Integer.valueOf(getStatistic(2));
        float gamesWon = Integer.valueOf(getStatistic(3));
        
        //calulate the ratio of wins to losses
        float winLoss = gamesWon / gamesPlayed;
        if (gamesWon == 0 && gamesPlayed == 0) {
            winLoss = 0;
        }

        //declare method to round decimal to 2 decimal places 
        DecimalFormat df = new DecimalFormat();
        df.setMaximumFractionDigits(2);
        //set the correct text field to the result of the calculation 
        winLossfld.setText(df.format(winLoss));
    }

    public void setDefaultStatistics() throws IOException {    
        //write the new number of the specified statistic 
        String filePath = "P:\\Component 3\\ProjectTest\\User Files\\" + accountName + ".txt";
        //Create new file to contain this users' details with username as name
        File file = new File(filePath);
        //declare a list of all the lines in the file
        List<String> lines = Files.readAllLines(file.toPath());
        //change list element at index 1 to the default statisic
        System.out.println(lines.size());
        lines.add("0");
        lines.add("0");
        lines.add("0");
        //write the file using the updated list
        Files.write(file.toPath(), lines);
    }
}
