/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainGame;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author 18JBond
 */
public class EasyGridGenerated_PlaceMinesTestV2 extends javax.swing.JFrame {

    int columns = 16;
    int rows = 16;

    int totalMineCount = 40;
    int[][] buttons_As_Mines;//-1 is a mine, -2 is a cleared space, 0 means no mines nearby
    boolean[][] buttons_cleared = new boolean[rows][columns];
    boolean game_in_progress = false;
    JButton[][] buttons;
    int flagged = 0;

    /**
     * Creates new form EasyGridGenerated_PlaceMinesTestV2
     */
    public EasyGridGenerated_PlaceMinesTestV2() {
        initComponents();
        generateGrid();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GamePnl = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GamePnl.setBackground(new java.awt.Color(255, 255, 255));
        GamePnl.setPreferredSize(new java.awt.Dimension(900, 900));

        javax.swing.GroupLayout GamePnlLayout = new javax.swing.GroupLayout(GamePnl);
        GamePnl.setLayout(GamePnlLayout);
        GamePnlLayout.setHorizontalGroup(
            GamePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        GamePnlLayout.setVerticalGroup(
            GamePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GamePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(GamePnl, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyGridGenerated_PlaceMinesTestV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyGridGenerated_PlaceMinesTestV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyGridGenerated_PlaceMinesTestV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyGridGenerated_PlaceMinesTestV2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyGridGenerated_PlaceMinesTestV2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GamePnl;
    // End of variables declaration//GEN-END:variables
    private void generateGrid() {
        GamePnl.setLayout(new GridLayout(rows, columns));
        //Add the buttons to the panel's gridLayout 
        buttons = new JButton[rows][columns];
        for (int r = 0; r < rows; r++) {
            for (int c = 0; c < columns; c++) {
                JButton btn = new JButton();
                /*Variables to enable use of r and c as they cannot be directly 
                passed into the following action listener */
                int row = r;
                int col = c;
                //add an action listener for each button that is created 
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        //if this is the first button clicked of a game
                        if (game_in_progress == false) {
                            placeMines(row, col);
                            gridClear(row, col);
                            game_in_progress = true;
                        }
                        //if this location has a mine, call losing function  
                        if (buttons_As_Mines[row][col] == -1) {
                            buttons[row][col].setBackground(Color.red);
                            gameLoss();//to be changed to gameLossScreen()
                            //if index has no mine call grid-clearing function
                        } else {
                            gridClear(row, col);
                        }
                        //check whether the user has cleared all spaces
                        gameSuccessful();
                        //Provide the relevant mine numbers to the user
                        revealGridNumbers();
                    }
                });
                btn.addMouseListener(new MouseAdapter(){
                    @Override
                    public void mouseClicked(MouseEvent m){
                        if(SwingUtilities.isRightMouseButton(m)){
                            if (btn.getText() == "⚑"){
                                btn.setForeground(Color.BLACK);
                                btn.setText("");
                                flagged = flagged -1;
                            }else{
                                btn.setForeground(Color.red);
                                btn.setText("⚑"); 
                                flagged = flagged + 1;
                            }
                        }
                    }
                });
                btn.setBackground(Color.GREEN);
                buttons[r][c] = btn;
                GamePnl.add(btn);
            }
        }
    }

    //subroutine to update buttonsAsMines to contain the position of mines
    private void placeMines(int initialRow, int initialCol) {        
        //Initialisation 
        int generatedR;
        int generatedC;
        int mines = 0;
        buttons_As_Mines = new int[rows][columns];        
        /*loop to iterate while the number of mines placed in the 2D array for 
        the grid is less than totalMineCount*/
        while (mines < totalMineCount) {
            //Generate a random x and y coordinate
            generatedR = (int) (Math.random() * rows);
            generatedC = (int) (Math.random() * columns);
            /*if this position does not already have a mine and is not the initial 
            index clicked by the user*/
            if (buttons_As_Mines[generatedR][generatedC] != -1 
                    && (generatedR != initialRow || generatedC != initialCol) //centre
                    && (generatedR != initialRow -1 || generatedC != initialCol -1) //above left
                    && (generatedR != initialRow -1 || generatedC != initialCol) //above 
                    && (generatedR != initialRow -1 || generatedC != initialCol +1) //above right
                    && (generatedR != initialRow || generatedC != initialCol -1) //left
                    && (generatedR != initialRow || generatedC != initialCol +1) //right
                    && (generatedR != initialRow +1 || generatedC != initialCol -1)//below left
                    && (generatedR != initialRow +1 || generatedC != initialCol) //below
                    && (generatedR != initialRow  +1 || generatedC != initialCol +1) //below right
                    ) {
                buttons_As_Mines[generatedR][generatedC] = -1;
                //increment mines 
                mines += 1;
                //increment adjacent mine numbers 
                updateMineNumbers(generatedR, generatedC);
            }
        }
    }

    private void gameLoss() {
        game_in_progress = false;
        System.out.println("Mine Clicked, game window would change to prevent "
                + "further clicks from the user");
    }

    //subroutine to check if the grid has been fully cleared
    private void gameSuccessful() {
        //count is the number of cleared spaces in the grid 
        int count = 0;
        //total is the number of spaces in the grid (No. of rows * No. of cols)
        int total = buttons_cleared.length * buttons_cleared[0].length;
        //iterate through the indexes in the grid 
        for (int row = 0; row < buttons_cleared.length; row++) {
            for (int column = 0; column < buttons_cleared[row].length; column++) {
                if (buttons_cleared[row][column] == true) {
                    count = count + 1;
                }
            }
        }
        if (total - count == totalMineCount) {
            //change panel to win screen etc.
            System.out.println("Game Won, current panel would be changed");
        }
    }

    private void printArray2D(int[][] array) {
        for (int i = 0; i < array.length; i++) {
            for (int j = 0; j < array[i].length; j++) {
                System.out.print(array[i][j] + " ");
            }
            //after 5 iterations (1 whole row), begin the next row on a new line 
            System.out.println("");
        }
    }

    //subroutine to increment by 1, the adjacent grid spaces to a given index
    private void updateMineNumbers(int row, int column) {
        /*for each index, the index must be checked to see that it is in the 
        bounds of the current grid and that it does not also contain a mine*/
        //increment grid space to the left
        if (inBounds(row, column - 1) && buttons_As_Mines[row][column - 1] != -1) {
            buttons_As_Mines[row][column - 1] += 1;
        }
        //increment grid space to the right
        if (inBounds(row, column + 1) && buttons_As_Mines[row][column + 1] != -1) {
            buttons_As_Mines[row][column + 1] += 1;
        }
        //increment button directly above & its adjacent buttons left and right:
        /*
        loop iterates from -1 to 1. This checks the item at the column index to 
        the left of, on and tp the right of the given column index
         */
        for (int i = -1; i < 2; i++) {
            if (inBounds(row - 1, column + i) && buttons_As_Mines[row - 1][column + i] != -1) {
                buttons_As_Mines[row - 1][column + i] += 1;
            }
        }
        //increment button directly below & its adjacent buttons left and right
        for (int i = -1; i < 2; i++) {
            if (inBounds(row + 1, column + i) && buttons_As_Mines[row + 1][column + i] != -1) {
                buttons_As_Mines[row + 1][column + i] += 1;
            }
        }
    }

    //checks if the given index is within the bounds of the grid
    //returns true if the index exists and false if not
    private boolean inBounds(int r, int c) {
        if ((r <= rows - 1 && r >= 0) && (c <= columns - 1 && c >= 0)) {
            return true;
        }
        return false;
    }

    private void tempDisplayAllNumbers() {
        for (int i = 0; i < buttons.length; i++) {
            for (int j = 0; j < buttons[i].length; j++) {
                int x = buttons_As_Mines[i][j];
                buttons[i][j].setText(Integer.toString(x));
            }
        }
    }

    //subroutine to update the numbers in the grid
    //if a tile displays a number but there is not an uncleared tile in the surrounding 8 tiles then the number should be removed 
    //if there is an uncleared tile, show the number 
    private void revealGridNumbers() {
        //iterate through each button in the grid
        //the index of each button is given by [rows][columns]
        for (int row = 0; row < buttons.length; row++) {
            for (int column = 0; column < buttons[row].length; column++) {
                //if any of of the contained statments are true the if will execute 
                /*
                If a tile is clear and any of the 8 tiles around it are not clear 
                then the number of mines around it should be displayed  
                 */
                //if a tile is cleared, move on to check the surrounding tiles 
                if (buttons_cleared[row][column] == true) {

                    if ((inBounds(row - 1, column - 1) && buttons_cleared[row - 1][column - 1] == false)
                            ||//above left
                            (inBounds(row - 1, column) && buttons_cleared[row - 1][column] == false)
                            ||//above 
                            (inBounds(row - 1, column + 1) && buttons_cleared[row - 1][column + 1] == false)
                            ||//above right
                            (inBounds(row, column - 1) && buttons_cleared[row][column - 1] == false)
                            ||//left
                            (inBounds(row, column + 1) && buttons_cleared[row][column + 1] == false)
                            ||//right
                            (inBounds(row + 1, column - 1) && buttons_cleared[row + 1][column - 1] == false)
                            ||//below left
                            (inBounds(row + 1, column) && buttons_cleared[row + 1][column] == false)
                            ||//below middle
                            (inBounds(row + 1, column + 1) && buttons_cleared[row + 1][column + 1] == false) //below right
                            ) {
                        buttons[row][column].setText(Integer.toString(buttons_As_Mines[row][column]));
                        /*if there are no mines around a tile, remove the number 0 
                      that is displayed by it     
                         */
                    } else {
                        buttons[row][column].setText("");
                    }
                }
            }
        }
    }

    private void gridClear(int r, int c) {
        //set current mine to clear
        buttons_cleared[r][c] = true;
        buttons[r][c].setBackground(Color.cyan);
        if (buttons_As_Mines[r][c] == 0) {

            //Check Above
            /*check that the index is in bounds, that the index does not contain a mine,
            that the index is not already cleared and that the index has 0 adjacent mines*/
            if (inBounds(r - 1, c) && buttons_As_Mines[r - 1][c] != -1 && buttons_cleared[r - 1][c] != true) {
                //set the index to clear and make this change visible to the user 
                buttons_cleared[r - 1][c] = true;
                buttons[r - 1][c].setBackground(Color.cyan);
                /*the conditions that decide if the function should be called 
                recursively. Can be edited to change effectiveness of algorithm
                 */
                if (buttons_cleared[r - 1][c] == true) {
                    gridClear(r - 1, c);
                }
            }
            //Check above left
            if (inBounds(r - 1, c - 1) && buttons_As_Mines[r - 1][c - 1] != -1 && buttons_cleared[r - 1][c - 1] != true) {
                buttons_cleared[r - 1][c - 1] = true;
                buttons[r + - 1][c - 1].setBackground(Color.cyan);
                if (buttons_cleared[r - 1][c - 1] == true) {
                    gridClear(r - 1, c - 1);
                }
            }
            //Check above right
            if (inBounds(r - 1, c + 1) && buttons_As_Mines[r - 1][c + 1] != -1 && buttons_cleared[r - 1][c + 1] != true) {
                buttons_cleared[r - 1][c + 1] = true;
                buttons[r - 1][c + 1].setBackground(Color.cyan);
                if (buttons_cleared[r - 1][c + 1] == true) {
                    gridClear(r - 1, c + 1);
                }
            }
            //Check Below
            if (inBounds(r + 1, c) && buttons_As_Mines[r + 1][c] != -1 && buttons_cleared[r + 1][c] != true) {
                buttons_cleared[r + 1][c] = true;
                buttons[r + 1][c].setBackground(Color.cyan);
                if (buttons_cleared[r + 1][c] == true) {
                    gridClear(r + 1, c);
                }
            }
            //Check below left
            if (inBounds(r + 1, c - 1) && buttons_As_Mines[r + 1][c - 1] != -1 && buttons_cleared[r + 1][c - 1] != true) {
                buttons_cleared[r + 1][c - 1] = true;
                buttons[r + 1][c - 1].setBackground(Color.cyan);
                if (buttons_cleared[r + 1][c - 1] == true) {
                    gridClear(r + 1, c - 1);
                }
            }
            //Check below right
            if (inBounds(r + 1, c + 1) && buttons_As_Mines[r + 1][c + 1] != -1 && buttons_cleared[r + 1][c + 1] != true) {
                buttons_cleared[r + 1][c + 1] = true;
                buttons[r + 1][c + 1].setBackground(Color.cyan);
                if (buttons_cleared[r + 1][c + 1] == true) {
                    gridClear(r + 1, c + 1);
                }
            }
            //Check Left 
            if (inBounds(r, c - 1) && buttons_As_Mines[r][c - 1] != -1 && buttons_cleared[r][c - 1] != true) {
                buttons_cleared[r][c - 1] = true;
                buttons[r][c - 1].setBackground(Color.cyan);
                if (buttons_cleared[r][c - 1] == true) {
                    gridClear(r, c - 1);
                }
            }
            //Check Right
            if (inBounds(r, c + 1) && buttons_As_Mines[r][c + 1] != -1 && buttons_cleared[r][c + 1] != true) {
                buttons_cleared[r][c + 1] = true;
                buttons[r][c + 1].setBackground(Color.cyan);
                if (buttons_cleared[r][c + 1] == true) {
                    gridClear(r, c + 1);
                }
            }
        }
    }

}
