package MainGame;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author 18Jbond
 */

public class EasyGrid extends javax.swing.JFrame {

    /**
     * Creates new form EasyGrid
     */
    //VARIABLE INITIALISATION
    //spaces cleared represents the number of tiles that the user has cleared 
    int spacesCleared = 0;
    /*totalMineCount will hold the total number of mines in the grid. It is 
    deternimed by the difficulty. As I am using seperate grids for each of the 3
    difficulty settings, the Mine count can be hardcoded in each jFrame
     */
    int totalMineCount = 10;
    /*The array buttonsAsMines is equal in length to the number of mines in the grid.
    Its value will be hardcoded in the jFrame file for each difficulty
     */
    boolean[][] buttonsAsMines = new boolean[10][10];
    ArrayList<JButton> btnList;

    public EasyGrid() {
        //populate the buttonArray with the buttons
        initComponents();
        btnList = new ArrayList<>();
        addButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GridButtons = new javax.swing.ButtonGroup();
        BasePnl = new javax.swing.JPanel();
        gridBtn0 = new javax.swing.JButton();
        gridBtn1 = new javax.swing.JButton();
        gridBtn2 = new javax.swing.JButton();
        gridBtn3 = new javax.swing.JButton();
        gridBtn4 = new javax.swing.JButton();
        gridBtn5 = new javax.swing.JButton();
        gridBtn6 = new javax.swing.JButton();
        gridBtn7 = new javax.swing.JButton();
        gridBtn8 = new javax.swing.JButton();
        gridBtn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BasePnl.setPreferredSize(new java.awt.Dimension(500, 500));
        BasePnl.setLayout(new java.awt.GridLayout(10, 10));

        GridButtons.add(gridBtn0);
        gridBtn0.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn0.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn0.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn0ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn0);

        GridButtons.add(gridBtn1);
        gridBtn1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn1.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn1.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn1ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn1);

        GridButtons.add(gridBtn2);
        gridBtn2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn2.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn2.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn2ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn2);

        GridButtons.add(gridBtn3);
        gridBtn3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn3.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn3.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn3ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn3);

        GridButtons.add(gridBtn4);
        gridBtn4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn4.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn4.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn4ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn4);

        GridButtons.add(gridBtn5);
        gridBtn5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn5.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn5.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn5ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn5);

        GridButtons.add(gridBtn6);
        gridBtn6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn6.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn6.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn6ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn6);

        GridButtons.add(gridBtn7);
        gridBtn7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn7.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn7.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn7ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn7);

        GridButtons.add(gridBtn8);
        gridBtn8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn8.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn8.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn8ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn8);

        GridButtons.add(gridBtn9);
        gridBtn9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        gridBtn9.setMaximumSize(new java.awt.Dimension(0, 0));
        gridBtn9.setMinimumSize(new java.awt.Dimension(0, 0));
        gridBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridBtn9ActionPerformed(evt);
            }
        });
        BasePnl.add(gridBtn9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BasePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BasePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gridBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn0ActionPerformed
        /*Change the displayed chracteristics of the button to make it clear to 
        the user which button they have clicked*/
        //gridBtn0.setBackground(java.awt.Color.cyan);
        //If this is the first click of the game, assign mine positions
        if (spacesCleared == 0) {
            placeMines();
        }/*else, if the tile contains a mine, end the game and bring up the loss
        screen
        else, (this is not the first move of the game and the tile is not a mine
        ), update the number displated by the tile to the number of mines around 
        it*/
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn0ActionPerformed

    private void gridBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn1ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn1ActionPerformed

    private void gridBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn2ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn2ActionPerformed

    private void gridBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn3ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn3ActionPerformed

    private void gridBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn4ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn4ActionPerformed

    private void gridBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn5ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn5ActionPerformed

    private void gridBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn6ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn6ActionPerformed

    private void gridBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn7ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn7ActionPerformed

    private void gridBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn8ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn8ActionPerformed

    private void gridBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridBtn9ActionPerformed
        int buttonNum = getButton(evt);
        System.out.println(buttonNum);
    }//GEN-LAST:event_gridBtn9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyGrid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyGrid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasePnl;
    private javax.swing.ButtonGroup GridButtons;
    private javax.swing.JButton gridBtn0;
    private javax.swing.JButton gridBtn1;
    private javax.swing.JButton gridBtn2;
    private javax.swing.JButton gridBtn3;
    private javax.swing.JButton gridBtn4;
    private javax.swing.JButton gridBtn5;
    private javax.swing.JButton gridBtn6;
    private javax.swing.JButton gridBtn7;
    private javax.swing.JButton gridBtn8;
    private javax.swing.JButton gridBtn9;
    // End of variables declaration//GEN-END:variables

    //subroutine to update buttonsAsMines to contain the position of mines
    private void placeMines() {
        //Initialisation 
        int positionX;
        int positionY;
        int mines = 0;
        /*loop to iterate while the number of mines placed in the 2D array for 
        the grid is less than totalMineCount*/
        while (mines < totalMineCount) {
            //Generate a random x and y coordinate
            positionX = (int) (Math.random() * 10);
            positionY = (int) (Math.random() * 10);
            //if this position does not already have a mine, place a mine there
            if (!buttonsAsMines[positionX][positionY]) {
                buttonsAsMines[positionX][positionY] = true;
                //increment 
                mines += 1;
            }
        }
    }

    /*gameLost() currently closes the game, in the final version of the project
    it will change the game tab to a loss tab*/
    private void gameLost() {
        System.exit(0);
    }

    private int getButton(ActionEvent evt) {
        for (JButton btn : btnList){
            //System.out.println(btnList.indexOf(btn));//TESTING
            if (evt.getSource()== btn){
                return btnList.indexOf(btn);                
            }
        }
        return -1123123;
    }

    private void addButtons() {
        btnList.add(gridBtn0);
        btnList.add(gridBtn1);
        btnList.add(gridBtn2);
        btnList.add(gridBtn3);
        btnList.add(gridBtn4);
        btnList.add(gridBtn5);
        btnList.add(gridBtn6);
        btnList.add(gridBtn7);
        btnList.add(gridBtn8);
        btnList.add(gridBtn9);
        
    }

}
